Extend Apply verb to extensions, Bump to K8s 1.22.
knative/pkg pull request #2327
Opened 2021-10-26 18:36 UTC by mattmoor

This was motivated by the linked issue, and does the work to upgrade PKG to 1.22 libs.

Fixes: https://github.com/knative/pkg/issues/2320

/kind enhancement
/hold

HOLDing this until we're clear that we *should* be bumping to 1.22 libs

**Release Note**

```release-note
Bump to K8s 1.22 libs
```

**Docs**
```docs

```

2021-11-14 14:32 UTC, antoineco commented
@mattmoor I didn't look into the details, but is anything stopping us from updating the code generator (add the `Apply` method) without actually pulling 1.22 dependencies into Knative yet?

This would allow an upgrade in two steps, and downstream could update their generated code ahead of time while upstream takes the time to do what's necessary.

Prometheus [recently bumped their dependencies](https://github.com/prometheus/prometheus/blob/v2.31.1/go.mod#L74-L76), which means it is now difficult to depend both on Knative and (up-to-date) Prometheus.

2021-11-14 16:41 UTC, mattmoor commented
I paged out a lot of the context here, but I think there was something (new type?).  You are welcome to try splitting pieces off of this.

2021-11-15 23:48 UTC, antoineco commented
Right, the new `ApplyScale()` method has the following [signature](https://github.com/kubernetes/kubernetes/blob/v1.22.3/staging/src/k8s.io/client-go/kubernetes/typed/apps/v1/deployment.go#L59):

```go
// import applyconfigurationsautoscalingv1 "k8s.io/client-go/applyconfigurations/autoscaling/v1"

ApplyScale(
	ctx context.Context,
	objectName string,
	scale *applyconfigurationsautoscalingv1.ScaleApplyConfiguration,
	opts metav1.ApplyOptions,
) (*autoscalingv1.Scale, error)
```

The type [`applyconfigurationsautoscalingv1.ScaleApplyConfiguration`](https://github.com/kubernetes/kubernetes/blob/v1.22.3/staging/src/k8s.io/client-go/applyconfigurations/autoscaling/v1/scale.go#L27-L34) was first introduced in Kubernetes `v1.22.0` 🧐 

So no choice but to update the libs.

Do you have cycles to rebase or would you prefer me to take over in a separate PR?

2021-11-15 23:50 UTC, mattmoor commented
I'm happy to rebase if we're 👍  on bumping, I just wanted to minimize that number if it was going to be a while.

2021-11-15 23:57 UTC, antoineco commented
@markusthoemmes based on your experience bumping k8s from 1.20 to 1.21, do you remember any specific issue downstream in the process?

2021-11-16 07:55 UTC, markusthoemmes commented
Not that I recall. Once we bump here, we're fine downstream usually.

2021-12-17 03:11 UTC, nak3 commented
1.1 was released. @dprotaso Is this ready to go now?

2021-12-17 03:12 UTC, mattmoor commented
I can try to dust off this PR over the weekend if we are cool with the bump next release.

2021-12-29 19:02 UTC, mattmoor commented
Walking thru failures:
 * Tekton - all legs: failures applying patch they are carrying
 * Eventing: downstream has a problem with a breaking `trace` change: https://github.com/knative/pkg/runs/4661167676?check_suite_focus=true#step:7:491
 * Eventing Kafka (both): has same problem as above: https://github.com/knative/pkg/runs/4661168049?check_suite_focus=true#step:7:336
 * Eventing KEDA: downstream has K8s pinned https://github.com/knative-sandbox/eventing-autoscaler-keda/blob/04b969d0a9afcd2f9a73ff0aa5a7326130323918/go.mod#L23-L30
 * Eventing Redis: downstream has an OTel conflict: https://github.com/knative/pkg/runs/4661168191?check_suite_focus=true#step:7:160

I'll TAL at what we need to fix Eventing, and I already started a thread in Tekton slack to pre-flight bumping their dependency to fix this.

2021-12-29 19:28 UTC, mattmoor commented
From the OTel CHANGELOG:
> The concept of a remote and local Span stored in a context is unified to just the current Span. Because of this "go.opentelemetry.io/otel/trace".RemoteSpanContextFromContext is removed as it is no longer needed. Instead, "go.opentelemetry.io/otel/trace".SpanContextFromContex can be used to return the current Span. If needed, that Span's SpanContext.IsRemote() can then be used to determine if it is remote or not. (#1731)

2021-12-30 13:15 UTC, mattmoor commented
The eventing issue seems resolved, so I expect the kafka repos to be unblocked once their dependency on eventing is bumped (both have 9+ day old PRs with e2e failures/flakes)

2022-01-03 17:15 UTC, mattmoor commented
Ok, so KEDA is fixed by: https://github.com/knative-sandbox/eventing-autoscaler-keda/pull/223

This leaves the 2x Kafka failures, 3x Tekton failures, and the codecov leg, which always seems to fail.

I'm inclined to try to get this merged...

2022-01-03 17:16 UTC, mattmoor commented
/unhold

2022-01-03 23:21 UTC, mattmoor commented
/assign @nak3 @dprotaso

2022-01-03 23:40 UTC, nak3 commented
LGTM :tada:

2022-01-04 16:06 UTC, mattmoor commented
cc @n3wscott for codegen changes

2022-01-04 16:31 UTC, dprotaso commented on go.mod
> +	k8s.io/api v0.22.2
probably want to bump to the latest patch now `v0.22.5`

2022-01-04 16:32 UTC, dprotaso requested changes
we should bump to the latest patch which is `0.22.5`

2022-01-04 17:05 UTC, mattmoor commented
@dprotaso done.  I'm going to stage a PR to tekton/pipelines to confirm we'll be good there, but this is RFAL.

2022-01-04 18:57 UTC, dprotaso commented
/lgtm
/approve

2022-01-04 18:58 UTC, merged