add admissionRequest in ctx
knative/pkg pull request #2718
Opened 2023-04-07 10:36 UTC by rahulii

# Changes

-  :broom: This PR associated the admissionv1.AdmissionRequest object the webhook received with the context.
-  adds a unit test

/kind <kind>

Fixes #2656 

**Release Note**

**Docs**

2023-04-07 15:45 UTC, dprotaso requested changes
We should remove the HTTP request from the context in favour of the AdmissionRequest

2023-04-07 15:45 UTC, dprotaso commented on apis/contexts.go
> +type AdmissionReq struct{}
don't expore this
```suggestion
type admissionRequest struct{}
```

2023-04-11 08:49 UTC, rahulii commented
> We should remove the HTTP request from the context in favour of the AdmissionRequest

https://github.com/knative/pkg/blob/main/webhook/conversion.go#L59
converion webhook also uses this function - we would not be able to remove it I guess unless we also support `Request *ConversionRequest`

2023-04-12 13:56 UTC, dprotaso commented
> conversion webhook also uses this function - we would not be able to remove it I guess unless we also support Request *ConversionRequest

Yeah let's do that and add helpers for `ConversionReview`

2023-08-02 16:14 UTC, closed without merging