Add AuthStatus type
knative/pkg pull request #2829
Opened 2023-09-20 12:34 UTC by karthikmurali60

# Changes

- :gift: Add new feature
- This PR adds a new AuthStatus type which currently contains the ServiceAccountName attribute, which is used for OIDC authentication

/kind api-change

Fixes https://github.com/knative/eventing/issues/7173

**Release Note**

```release-note
Add AuthStatus type
```

**Docs**

```docs

```

2023-09-20 12:37 UTC, karthikmurali60 commented
@pierDipi can you please review this PR?

2023-09-20 13:50 UTC, pierDipi reviewed
Thanks @karthikmurali60!

/approve

/cc @creydr

2023-09-20 13:50 UTC, pierDipi commented
/ok-to-test

2023-09-20 13:50 UTC, pierDipi commented
/ok-to-test

2023-09-20 14:09 UTC, creydr requested changes

2023-09-20 14:09 UTC, creydr commented on apis/duck/v1/auth_types.go
> +
```suggestion
```
I think we don't need this

2023-09-20 15:40 UTC, creydr commented
@karthikmurali60 you have to run `hack/update-codegen.sh` as you updated the types

2023-09-20 16:39 UTC, karthikmurali60 commented
@creydr I ran the script and committed the generated files. Still some of the tests are failing, this is because of the missing functions in `auth_types.go` file. I am trying to add them

2023-09-21 06:02 UTC, creydr commented
Hey @karthikmurali60,
seems the generated file was not updated in your [latest push](https://github.com/knative/pkg/compare/f71397e06238450b4203dda2b77a5977767291a3..999ce35e0d1e401d57c84d36815852f0ad373bbb). 
When I run the `hack/update-codegen.sh` on your branch I see some changes. So I think running it and pushing all the files should fix the build issues.

2023-09-21 15:33 UTC, karthikmurali60 commented
@creydr I ran `hack/update-codegen.sh` on this branch and pushed the changes in [this](https://github.com/knative/pkg/pull/2829/commits/5c0b353b9e538c1e51100b51be32c6723203b1e9) commit. However, the same tests are still failing. I am not able to find out why this is happening. Any thoughts ?

2023-09-21 20:29 UTC, dprotaso commented
Error states
```
=== Errors
client/injection/ducks/duck/v1/authstatus/authstatus.go:44:37: (&v1.AuthStatus{}).GetFullType undefined (type *"knative.dev/pkg/apis/duck/v1".AuthStatus has no field or method GetFullType)
```

2023-09-22 06:09 UTC, creydr commented
> Error states
> 
> ```
> === Errors
> client/injection/ducks/duck/v1/authstatus/authstatus.go:44:37: (&v1.AuthStatus{}).GetFullType undefined (type *"knative.dev/pkg/apis/duck/v1".AuthStatus has no field or method GetFullType)
> ```

@karthikmurali60 It seems this issue is because you had the `+genduck` annotation, when you run update-codegen.sh initially (and it seems update-codegen does not update client/injection/... :shrug: ). 
I would remove the generated files from `client/injection/ducks/duck/v1/authstatus` and rerun update-codegen.sh.

2023-09-22 06:49 UTC, karthikmurali60 commented
@creydr this was the issue, thanks a lot for pointing that out. I have fixed it and pushed the new changes. 

> > Error states
> > ```
> > === Errors
> > client/injection/ducks/duck/v1/authstatus/authstatus.go:44:37: (&v1.AuthStatus{}).GetFullType undefined (type *"knative.dev/pkg/apis/duck/v1".AuthStatus has no field or method GetFullType)
> > ```
> 
> @karthikmurali60 It seems this issue is because you had the `+genduck` annotation, when you run update-codegen.sh initially (and it seems update-codegen does not update client/injection/... 🤷 ). I would remove the generated files from `client/injection/ducks/duck/v1/authstatus` and rerun update-codegen.sh.

2023-09-22 07:21 UTC, creydr commented
> @creydr this was the issue, thanks a lot for pointing that out. I have fixed it and pushed the new changes.

Awesome :tada: Lets wait for the other checks to pass and then we should be ready to go :+1:

2023-09-22 07:27 UTC, creydr commented on apis/duck/v1/auth_types.go
@karthikmurali60 seems the boilerplate does not match the template (some missing lines, etc.). You can check on https://github.com/knative/pkg/blob/main/hack/boilerplate/boilerplate.go.txt for the format (just replace the year)

2023-09-22 11:04 UTC, karthikmurali60 commented
/rerun

2023-09-22 12:05 UTC, merged